spring.application.name=peakWell
spring.datasource.url=jdbc:mysql://localhost:3306/peakwell?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server configuration :
server.port=8090
server.servlet.context-path=/peakwell

# keycloak configuration
keycloak.server-url=http://localhost:8080
keycloak.realm=peakwell
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/peakwell
keycloak.client-id=spring-client
keycloak.client-id.front=angular-client
keycloak.client-secret=9xbaTaAY6m1NNaQ9JiPAf0fx1wWwXeY7

app.verify-email-redirect-url=http://localhost:4200/auth/login
app.frontend.url=http://localhost:4200

#config cloudinary 
cloudinary.cloud_name=dbmb50bso
cloudinary.api_key=732399514587359
cloudinary.api_secret=srfRQHDtG4T-8LzSHI593GKmJDA

#congigure mail service 

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hazemhadda123@gmail.com
spring.mail.password=gjeo ncxh thsl ojss

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true